---
# Copyright 2020 Orange
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.


# tasks file for kube-prometheus-phase


- name: Copy manifests files from the installer to the kube-masters
  copy:
      src: "{{ playbook_dir }}/kube-prometheus/manifests/"
      dest: "{{ manifest_dir }}"


- name: Apply Custom Resource Definitions (CRD) from Kube-Prometheus
  command: "kubectl --kubeconfig {{ kubeconf_path }} apply -f {{ manifest_dir }}/setup/"


- name: Apply manifests from Kube-Prometheus
  command: "kubectl --kubeconfig {{ kubeconf_path }} apply -f {{ manifest_dir }}"

