---
- hosts: localhost
  gather_facts: false
  become: yes
  roles: 
    - { role: prep }


- hosts: k8s-cluster
  gather_facts: true
  become: yes
  roles: 
     - { role: reset }


- import_playbook: kubespray/reset.yml

- import_playbook: kubespray/remove-node.yml
