# This template is based on the Kubespray inventory (https://github.com/kubernetes-sigs/kubespray/blob/master/inventory/sample/inventory.ini)
# Inventory sample of a pool of 3 servers with :
# - cartmann as "master"
# - node1, node2 and node3 as "worker"

# ## Configure 'ip' variable to bind kubernetes services on a
# ## different ip than the default iface
# ## We should set etcd_member_name for etcd cluster. The node that is not a etcd member do not need to set the value, or can set the empty string value.
all:
    cartmann:
        ansible_host: localhost
        ip: localhost
        access_ip: localhost
        etcd_member_name=etcd1
    node1: #kenny
        ansible_host: 10.8.0.2
        ip: 10.8.0.2
        access_ip: 10.8.0.2
        etcd_member_name=etcd2
    node2: #kyle
        ansible_host: 10.8.0.3
        ip: 10.8.0.3
        access_ip: 10.8.0.3
        etcd_member_name=etcd3
    node3: #stan:
        ansible_host: 10.8.0.4
        ip: 10.8.0.4
        access_ip: 10.8.0.4
        etcd_member_name=etcd4
    # node1 ansible_host=95.54.0.12  # ip=10.3.0.1 etcd_member_name=etcd1
    # node2 ansible_host=95.54.0.13  # ip=10.3.0.2 etcd_member_name=etcd2
    # node3 ansible_host=95.54.0.14  # ip=10.3.0.3 etcd_member_name=etcd3
    # node4 ansible_host=95.54.0.15  # ip=10.3.0.4 etcd_member_name=etcd4
    # node5 ansible_host=95.54.0.16  # ip=10.3.0.5 etcd_member_name=etcd5
    # node6 ansible_host=95.54.0.17  # ip=10.3.0.6 etcd_member_name=etcd6

    # ## configure a bastion host if your nodes are not directly reachable
    # [bastion]
    # bastion ansible_host=x.x.x.x ansible_user=some_user

kube_control_plane:
    cartmann

etcd:
    cartmann

kube_node:
    node1
    node2
    node3
    #node4
    # node5
    # node6

calico_rr:

k8s_cluster:children
    kube_control_plane
    kube_node
    calico_rr
