# This template is based on the Kubespray inventory (https://github.com/kubernetes-sigs/kubespray/blob/master/inventory/sample/inventory.ini)
# Inventory sample of a pool of 3 servers with :
# - node1 as "master"
# - node2 and node3 as "worker"


all:
  hosts:
# List here all servers within the cluster.
# For the sake of clarity and to ease the K8s clustering, 
# the NMaaS has been tested on top of a VPN overlaying several LANs.
# If not familiar, just use the same subnet for the IP_ADDRESS of each server as such :
    cartmann:
      ansible_host: localhost
      ip: localhost
      access_ip: localhost
    node1: #kenny
      ansible_host: 10.8.0.2
      ip: 10.8.0.2
      access_ip: 10.8.0.2
    node2: #kyle
      ansible_host: 10.8.0.3
      ip: 10.8.0.3
      access_ip: 10.8.0.3
    node3: #stan:
      ansible_host: 10.8.0.4
      ip: 10.8.0.4
      access_ip: 10.8.0.4

  children:
    kube_master:
      hosts:
        cartmann:
          
    kube_node:
      hosts:
        node1:
        node2:
        node3:

    etcd:
      hosts:
        cartmann:

    k8s_cluster:
      children:
        kube_master:
        kube_node:
    calico_rr:
      hosts: {}
